## ----------- PRÉ-REQUISITOS -----------
## POSTGRESQL   - https://www.postgresql.org/download/windows/

version: "3"
services:
  db:
    image: "postgres:buster"
    container_name: "pg_container"
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=test_db
    ports:
        - "55432:5432"
    volumes:
        - "/mnt/C/Users/altamiro.sousa/OneDrive/PARTICULAR/Cursos/Bootcampo - Eng.Dados/A003-SQL/04-SQL+Select+Where+Group_by_(Parte_02)/db:/var/lib/postgresql/data/"
        
## ----------- COMANDOS -----------
## POSICIONA PASTA        - cd A003-SQL\04-SQL+Select+Where+Group_by_(Parte_02)
## SUBIR SERVIÇOS         - docker-compose up db (modo console)
##                        - docker-compose up -d db (modo "serviço")

## VERIFICAR SERVIÇOS     - docker-compose ps

