## ----------- PRÉ-REQUISITOS -----------
## POSTGRESQL   - https://www.postgresql.org/download/windows/

version: "3"
services:
  db:
    image: postgres
    container_name: "pg_container"
    environment:
        - POSTGRESS_USER=root
        - POSTGRESS_PASSWORD=root
        - POSTGRESS_DB=test_db
    ports:
        - "5432:5432"
    volumes:
        - ".db:/var/lib/postgres/data/"

## ----------- COMANDOS -----------
## POSICIONA PASTA        - cd A003-SQL\02-Docker_Compose
## SUBIR SERVIÇOS         - docker-compose up db


